FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y git perl python3 make autoconf g++ flex bison ccache
RUN apt-get install -y libgoogle-perftools-dev numactl perl-doc
RUN apt-get install -y libfl2  # Ubuntu only (ignore if gives error)
RUN apt-get install -y libfl-dev  # Ubuntu only (ignore if gives error)
RUN apt-get install -y zlib1g zlib1g-dev

# Install verilator
RUN git clone https://github.com/verilator/verilator
RUN unset VERILATOR_ROOT
RUN cd verilator && git pull
RUN cd verilator && autoconf
RUN cd verilator && ./configure
RUN cd verilator && make -j 250; exit 0

RUN apt-get install -y help2man
RUN cd verilator && make install

# Install sv2v
RUN apt-get install -y curl
RUN curl -sSL https://get.haskellstack.org/ | sh -s - -f
RUN git clone https://github.com/zachjs/sv2v.git
RUN cd sv2v; make -j 250
ENV PATH="${PATH}:/sv2v/bin"

# Install yosys
RUN apt-get -y install build-essential clang bison flex libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev
RUN git clone https://github.com/YosysHQ/yosys.git
RUN cd yosys && make -j 250
RUN cd yosys && make install

# Fix a problem with Verilator
RUN sed -i 's/std/std2/' /usr/local/share/verilator/include/verilated_std.sv

RUN git clone https://github.com/flaviens/cva6_yosys_issue
RUN cd cva6_yosys_issue && make run_vanilla
RUN cd cva6_yosys_issue && make run_instrumented
